mkdir %CD%\"Datasheets"
mkdir %CD%\"Firmware"
mkdir %CD%\"Hardware\Gerbers"
mkdir %CD%\"Hardware\KiCAD_Project_Files"
mkdir %CD%\"Hardware\KiCAD_Project_Archive"
mkdir %CD%\"Hardware\Gerber_Archive"
mkdir %CD%\"Rendered_Pics"
